### ISSUE TITLE
Avatar - Self-mute ability 

### ISSUE THREAD

**Issue by branchbark** [JJSI/805#13]
Is it possible to make some of these tools available in the HoloLens side of the app? They could be useful for troubleshooting too. There is a mute option there already, though it may mute speakers at the same time (needs to be tested):

![mrh6jun-2](https://user-images.githubusercontent.com/20303688/27061863-2dc1c0a8-4fb5-11e7-8789-8de9587c1f3e.JPG)

**Comment by mr0ng** [comment]
Added in #38
