### ISSUE TITLE
Add Photon Server API Key to JJSInnovations

### ISSUE THREAD

**Issue by branchbark** [JJSI/805#27]
- [x] Configure API key settings
- [x] Remove from HoloCracy GitHub Source

**Comment by branchbark** [comment]
Sean will create a new Photon account for JJSInnovations

**Comment by mr0ng** [comment]
Registered for a new photon account under JJS, but it will take a few days from them to confirm my e-mail. I'll continue to monitor our outlook e-mail for an e-mail from Photon. Team, please also keep an eye out. Last time, they took about 3 days to get back to me. In the interim, we can continue testing with our old API key, or I can create a new API key under my personal account.

**Comment by JJSInnovations** [comment]
Replying from Outlook to see how it works.


I am ok to monitor email and organize it for now.


Julie


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by branchbark** [comment]
Merged the PR Sean had submitted into the master source.

**Comment by mr0ng** [comment]
Still no e-mail from Photon as of 6/18/2017

**Comment by mr0ng** [comment]
Photon still has not gotten back to me about the new account. Will proceed with our new API key from my old account for Windows Store release. it will be easy to change later with no noticeable effect on users.
