### ISSUE TITLE
Add Practical Analytics API Key to JJSInnovations

### ISSUE THREAD

**Issue by branchbark** [JJSI/805#28]
- [x] Configure API key to JJSInnovations
- [x] Remove from HoloCracy GitHub Source

**Comment by branchbark** [comment]
Sean will update the Practical Analytics API key

**Comment by mr0ng** [comment]
Part of #34 
Already added JJSInnovations API Key from Practical Analytics.
We can keep the old Practical Analytics key on the old GitHub.
