### ISSUE TITLE
Update 'Menu' Scene Title

### ISSUE THREAD

**Issue by branchbark** [JJSI/805#39]
Rename from MR Hangout to myxd3D

**Comment by juliedriver** [comment]
Also needs the blue outline frame.

**Comment by juliedriver** [comment]
Could subtitle be something different?

![main-menu-text-suggestion1](https://user-images.githubusercontent.com/20303688/27341720-1291a300-55ac-11e7-9c77-bf5b1322ee1f.JPG)

![main-menu-text-suggestion2](https://user-images.githubusercontent.com/20303688/27341732-17778c40-55ac-11e7-909b-da26abdd4986.JPG)

**Comment by branchbark** [comment]
Done
