### ISSUE TITLE
Windows Store App Publishing - Windows App Certification Kit Fail

### ISSUE THREAD

**Issue by branchbark** [JJSI/805#5]
The app currently uses APIs that are not part of the Windows SDK:

![image](https://user-images.githubusercontent.com/5480431/27207059-bda52cea-5209-11e7-8a0b-6b2b57af9c88.png)

Error Found: The supported APIs test detected the following errors:
API OpenSemaphore in api-ms-win-core-synch-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API CreateSemaphore in api-ms-win-core-kernel32-legacy-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API D3D12GetDebugInterface in d3d12.dll is not supported for this application type. UnityPlayer.dll calls this API.
API ExecuteAssembly in uwphost.dll is not supported for this application type. Mixed Reality Hangout.exe calls this API.
API DllGetActivationFactory in uwphost.dll is not supported for this application type. Mixed Reality Hangout.exe has an export that forwards to this API.

**Comment by mr0ng** [comment]
Should be solved when building as Master instead of Release. Will try it out to confirm.

**Comment by branchbark** [comment]
![image](https://user-images.githubusercontent.com/5480431/27416608-7f6e73c8-56dc-11e7-8d89-9b29745a497d.png)

**Comment by branchbark** [comment]
![image](https://user-images.githubusercontent.com/5480431/27416758-7dcf347a-56dd-11e7-803f-b8ed955f4593.png)

**Comment by branchbark** [comment]
thynq3D

**Comment by branchbark** [comment]
New developer account created for thynq3D from Microsoft account.
